### ISSUE TITLE
handler.go 269-270

### ISSUE THREAD

**Issue by kyanachana** [Airi-hub/mercari-build-hackathon-2023#5]
not found handlingの箇所を直します．いっぱいあるので簡単に応用できそうなら他の箇所も変更します．

https://github.com/Airi-hub/mercari-build-hackathon-2023/blob/178e52e642bb804c5c96f79914760213b307c4af/backend/handler/handler.go#LL269C1-L270C1

**Comment by Airi-hub** [comment]
了解です！ありがとうございます！
