### ISSUE TITLE
handler.go 140-141 / categoryを追加する機能

### ISSUE THREAD

**Issue by chronoll** [Airi-hub/mercari-build-hackathon-2023#9]
https://github.com/Airi-hub/mercari-build-hackathon-2023/blob/c8fb8f091c04e5cafcdc43c5df1c7ee4a089e1cf/backend/handler/handler.go#LL140C1-L141C31
該当箇所のTODO:validationを行います！

**Comment by Airi-hub** [comment]
LGTM
